<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>BrandUp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BrandUp.Core\BrandUp.Core.csproj" />
    <ProjectReference Include="..\..\src\BrandUp.Core.AspNetCore\BrandUp.Core.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\BrandUp.Core.Testing\BrandUp.Core.Testing.csproj" />
    <ProjectReference Include="..\..\src\BrandUp.Core.Testing.xUnit\BrandUp.Core.Testing.xUnit.csproj" />
    <ProjectReference Include="..\..\src\BrandUp.Core.FluentValidation\BrandUp.Core.FluentValidation.csproj" />
    <ProjectReference Include="..\..\src\BrandUp.Core.Outbox.MongoDB\BrandUp.Core.Outbox.MongoDB.csproj" />
  </ItemGroup>

</Project>
